### ISSUE TITLE
Update linked site

### ISSUE THREAD

**Issue by Hyperseeker** [ninest/readability-ui#5]
The GitHub site no longer works because it's linked to a different username: `themindstorm`, rather than your current `ninest`. (Cool username, by the way.)

There are two instances of it: in the repo title line, next to the description; and in the title line of README.md.

**Comment by ninest** [comment]
Thanks for the heads up! 

Also, I'm probably not going to update this. I've learned a lot since I made this, so I'll probably rewrite it
